Allow ESP root path to be configurable
If the system has the ESP(s) mounted at a path other than /boot,
the user can specify 'esp_root=<path>' while invoking the Makefile
targets to specify the necessary path.

Closes #1.

diff --git a/bootbind b/bootbind
--- a/bootbind
+++ b/bootbind
@@ -6,13 +6,13 @@ set -e
 shopt -s dotglob
 shopt -s lastpipe
 
-if mountpoint -q /boot; then
-	echo "/boot is already mounted, aborting..." 1>&2
+if mountpoint -q ${ESP_ROOT}; then
+	echo "${ESP_ROOT} is already mounted, aborting..." 1>&2
 	exit 1
 fi
 
-if ls /boot/* &> /dev/null; then
-	echo "/boot is not empty, aborting..." 1>&2
+if ls ${ESP_ROOT}/* &> /dev/null; then
+	echo "${ESP_ROOT} is not empty, aborting..." 1>&2
 	exit 1
 fi
 
@@ -34,15 +34,15 @@ if [[ -z $UUID ]]; then
 	exit 1
 fi
 
-findmnt -n -l --source "PARTUUID=$UUID" --output "target" | grep -m 1 "^/boot@[a-z]$" | read TRGT
+findmnt -n -l --source "PARTUUID=$UUID" --output "target" | grep -m 1 "^${ESP_ROOT}@[a-z]$" | read TRGT
 if [[ -z $TRGT ]]; then
-	echo "failed to find mountpoint of form /boot@[a-z] for current esp, aborting..." 1>&2
+	echo "failed to find mountpoint of form ${ESP_ROOT}@[a-z] for current esp, aborting..." 1>&2
 	exit 1
 fi
 
-mkdir -p /boot
+mkdir -p ${ESP_ROOT}
 
-chmod 0000 /boot &> /dev/null || true
-chcon -u system_u -r object_r -t boot_t -l s0 /boot &> /dev/null || true
+chmod 0000 ${ESP_ROOT} &> /dev/null || true
+chcon -u system_u -r object_r -t boot_t -l s0 ${ESP_ROOT} &> /dev/null || true
 
-mount -o bind $TRGT /boot
+mount -o bind $TRGT ${ESP_ROOT}
diff --git a/bootsync b/bootsync
--- a/bootsync
+++ b/bootsync
@@ -9,13 +9,13 @@ TEMPDIR=''
 function cleanup { [[ -n "$TEMPDIR" ]] && rm -rf $TEMPDIR; }
 trap cleanup exit
 
-if ! mountpoint -q /boot; then
-	echo "/boot is not a mountpoint, aborting..." 1>&2
+if ! mountpoint -q ${ESP_ROOT}; then
+	echo "${ESP_ROOT} is not a mountpoint, aborting..." 1>&2
 	exit 1
 fi
 
-if ! [[ -d /boot/loader ]]; then
-	echo "directory /boot/loader not found, aborting..." 1>&2
+if ! [[ -d ${ESP_ROOT}/loader ]]; then
+	echo "directory ${ESP_ROOT}/loader not found, aborting..." 1>&2
 	exit 1
 fi
 
@@ -26,15 +26,15 @@ if [[ -z $MACHINE_ID ]]; then
 fi
 
 ls -v /lib/modules | tail -n 1 | read LASTKRN
-if ! [[ -e /boot/$MACHINE_ID/$LASTKRN ]]; then
-	echo "$MACHINE_ID/$LASTKRN not found under /boot, aborting..." 1>&2
+if ! [[ -e ${ESP_ROOT}/$MACHINE_ID/$LASTKRN ]]; then
+	echo "$MACHINE_ID/$LASTKRN not found under ${ESP_ROOT}, aborting..." 1>&2
 	exit 1
 fi
 
-findmnt -n -l --output source /boot | read SRC
-findmnt -n -l --output target $SRC | grep -m 1 "^/boot@[a-z]$" | read TGT
+findmnt -n -l --output source ${ESP_ROOT} | read SRC
+findmnt -n -l --output target $SRC | grep -m 1 "^${ESP_ROOT}@[a-z]$" | read TGT
 if [[ -z $TGT ]]; then
-	echo "/boot does not appear to be a bind mount of /boot@[a-z], aborting..." 1>&2
+	echo "${ESP_ROOT} does not appear to be a bind mount of ${ESP_ROOT}@[a-z], aborting..." 1>&2
 	exit 1
 fi
 
@@ -46,7 +46,7 @@ fi
 
 mktemp -d | read TEMPDIR
 touch $TEMPDIR/$LASTKRN
-for m in $(ls -d /boot@[a-z]); do
+for m in $(ls -d ${ESP_ROOT}@[a-z]); do
 	mountpoint -q $m || continue
 	[[ $m == $TGT ]] && continue
 
@@ -59,5 +59,5 @@ for m in $(ls -d /boot@[a-z]); do
 		continue
 	fi
 
-	rsync $VERBOSITY -r --delete --include="*/" --include="**$MACHINE_ID**" --exclude="*" /boot/ $m
+	rsync $VERBOSITY -r --delete --include="*/" --include="**$MACHINE_ID**" --exclude="*" ${ESP_ROOT}/ $m
 done
