output to stderr by default
Signed-off-by: Gregory Bartholomew <gregory.lee.bartholomew@gmail.com>

diff --git a/bootbind b/bootbind
--- a/bootbind
+++ b/bootbind
@@ -1,40 +1,42 @@
 #!/usr/bin/bash
 # vim:set ts=3:
 
+exec 1>&2
+
 shopt -s dotglob
 shopt -s lastpipe
 
 if mountpoint -q "${ESP_ROOT}"; then
-	echo "${ESP_ROOT} is already mounted, aborting..." 1>&2
+	echo "${ESP_ROOT} is already mounted, aborting..."
 	exit 1
 fi
 
 if ls ${ESP_ROOT}/* &> /dev/null; then
-	echo "${ESP_ROOT} is not empty, aborting..." 1>&2
+	echo "${ESP_ROOT} is not empty, aborting..."
 	exit 1
 fi
 
 EFI_VARS="$(efibootmgr -v)"
 if [[ -z $EFI_VARS ]]; then
-	echo "failed to read efi variables, aborting..." 1>&2
+	echo "failed to read efi variables, aborting..."
 	exit 1
 fi
 
 echo "$EFI_VARS" | grep "^BootCurrent: " | read LABEL BOOT_ID
 if [[ -z $BOOT_ID ]]; then
-	echo "failed to determine current esp, aborting..." 1>&2
+	echo "failed to determine current esp, aborting..."
 	exit 1
 fi
 
 echo "$EFI_VARS" | grep "^Boot$BOOT_ID" | grep --perl-regexp -io '[0-9a-f-]{36}' | read UUID
 if [[ -z $UUID ]]; then
-	echo "failed to find current esp's partition uuid, aborting..." 1>&2
+	echo "failed to find current esp's partition uuid, aborting..."
 	exit 1
 fi
 
 findmnt -n -l --source "PARTUUID=$UUID" --output "target" | grep "^${ESP_ROOT}@[a-z]$" | read ESP_MOUNT
 if [[ -z $ESP_MOUNT ]]; then
-	echo "failed to find mountpoint of form ${ESP_ROOT}@[a-z] for current esp, aborting..." 1>&2
+	echo "failed to find mountpoint of form ${ESP_ROOT}@[a-z] for current esp, aborting..."
 	exit 1
 fi
 
diff --git a/bootsync b/bootsync
--- a/bootsync
+++ b/bootsync
@@ -1,37 +1,39 @@
 #!/usr/bin/bash
 # vim:set ts=3:
 
+exec 1>&2
+
 shopt -s lastpipe
 
 if ! mountpoint -q "${ESP_ROOT}"; then
-	echo "${ESP_ROOT} is not a mountpoint, aborting..." 1>&2
+	echo "${ESP_ROOT} is not a mountpoint, aborting..."
 	exit 1
 fi
 
 if ! [[ -d ${ESP_ROOT}/loader ]]; then
-	echo "directory ${ESP_ROOT}/loader not found, aborting..." 1>&2
+	echo "directory ${ESP_ROOT}/loader not found, aborting..."
 	exit 1
 fi
 
 if ! read MACHINE_ID < /etc/machine-id; then
-	echo "file /etc/machine-id is empty, aborting..." 1>&2
+	echo "file /etc/machine-id is empty, aborting..."
 	exit 1
 fi
 
 if ! ls -v -r /lib/modules | read LASTKRN; then
-	echo "failed to determine latest kernel version, aborting ..." 1>&2
+	echo "failed to determine latest kernel version, aborting ..."
 	exit 1
 fi
 
 if ! [[ -e ${ESP_ROOT}/$MACHINE_ID/$LASTKRN ]]; then
-	echo "$MACHINE_ID/$LASTKRN not found under ${ESP_ROOT}, aborting..." 1>&2
+	echo "$MACHINE_ID/$LASTKRN not found under ${ESP_ROOT}, aborting..."
 	exit 1
 fi
 
 findmnt -n -l --output "source" "${ESP_ROOT}" | read ESP_DEVICE
 findmnt -n -l --output "target" "$ESP_DEVICE" | grep "^${ESP_ROOT}@[a-z]$" | readarray -t ESP_MOUNT
 if [[ ${#ESP_MOUNT[@]} -ne 1 ]]; then
-	echo "${ESP_ROOT} does not appear to be a bind mount of exactly one ${ESP_ROOT}@[a-z] path, aborting..." 1>&2
+	echo "${ESP_ROOT} does not appear to be a bind mount of exactly one ${ESP_ROOT}@[a-z] path, aborting..."
 	exit 1
 fi
 
@@ -50,7 +52,7 @@ for esp in ${ESP_ROOT}@[a-z]; do
 		ls -v -r "$esp/$MACHINE_ID" | read LASTESP
 		printf "$LASTKRN\n$LASTESP\n" | sort -V -r | read GREATER
 		if [[ $GREATER != $LASTKRN ]]; then
-			echo "newer kernel detected on $esp, refusing to update..." 1>&2
+			echo "newer kernel detected on $esp, refusing to update..."
 			RETURN=1
 			continue
 		fi
